---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

# image will be published to ghcr.io/<user>/<name>
name: my-ublue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 43 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copies config/files/usr into your image's /usr.
          # put configuration files you want in /etc/ on a booted system 
          # in /usr/etc/ in the image. read more in files module reference.

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://packages.microsoft.com/yumrepos/vscode/config.repo
      - https://mise.jdx.dev/rpm/mise.repo
      - https://copr.fedorainfracloud.org/coprs/alternateved/keyd/repo/fedora-%OS_VERSION%/alternateved-keyd-fedora-%OS_VERSION%.repo
      # - https://developer.download.nvidia.com/compute/cuda/repos/fedora%OS_VERSION%/x86_64/cuda-fedora%OS_VERSION%.repo
      - eduvpn.repo
    keys:
      - https://app.eduvpn.org/linux/v4/rpm/app+linux@eduvpn.org.asc
    install:
      - tailscale
      - firefox
      - code
      - langpacks-en_GB
      - langpacks-nl
      - podman
      - distrobox
      - buildah
      - skopeo
      - podman-docker
      - chromium
      - mise
      - keyd
      ## Some native gnome applications:
      - gnome-calculator
      - gnome-calendar
      - gnome-clocks
      - gnome-text-editor
      - loupe
      - evince
      # - cuda-toolkit
      - virt-manager
      # - eduvpn-client
    remove: []

  - type: systemd
    system:
      enabled:
        - tailscaled

  - type: bling
    install:
      - 1password

  # Default flatpaks installed system-wide. User can install flatpaks in home as well
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        repo:
          title: Flathub (system)
        install:
          - org.gnome.Evolution
          - org.onlyoffice.desktopeditors
          - md.obsidian.Obsidian
          - com.nextcloud.desktopclient.nextcloud
          - com.usebottles.bottles
          - io.github.flattool.Warehouse

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
